apiVersion: v1
kind: Service
metadata:
  name: exosite
  labels:
    app: exosite
spec:
  ports:
    - port: 80
    - port: 443
  selector:
    app: exosite
  type: NodeIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exosite
  labels:
    app: exosite
spec:
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: exosite
    spec:
      containers:
      - name: discourse
        image: bitnami/discourse
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: POSTGRES_PASSWORD
          value: "admin"
        - name: POSTGRES_MASTER_HOST
          value: "ip.com"
        - name: REDIS_MASTER_HOST
          value: "ip.com"
        - name: REDIS_PASSWORD
          value: "REDIS_PASSWORD"
        - name: DISCOURSE_USERNAME
          value: "exorath"
        - name: DISCOURSE_PASSWORD
          value: "password"
        - name: DISCOURSE_EMAIL
          value: "exorathnetwork@gmail.com"
        - name: DISCOURSE_SITENAME
          value: "Exorath"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: 587
        - name: SMTP_USER
          value: "exorathnetwork@gmail.com"
        - name: SMTP_PASSWORD
          value: "password here"
