apiVersion: v1
kind: Service
metadata:
  name: exosite-postgres
  labels:
    app: exosite-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: exosite-postgres
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exosite-postgres
  labels:
    app: exosite-postgres
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: exosite-postgres
    spec:
      containers:
      - name: discourse
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "admin"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
      volumes:
      - name: postgresdata
        hostPath:
          path: /data
