apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exosite_postgres
  labels:
    app: exosite_postgres
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: exosite_postgres
    spec:
      containers:
      - name: discourse
        image: bitnami/discourse
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "admin"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdata
      volumes:
      - name: postgresdata
        hostPath:
          path: /data
