apiVersion: v1
kind: Service
metadata:
  name: exosite-redis
  labels:
    app: exosite-redis
spec:
  ports:
    - port: 6379
  selector:
    app: exosite-redis
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: exosite-redis
  labels:
    app: exosite-redis
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: exosite-redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redisdata
      volumes:
      - name: redisdata
        hostPath:
          path: ~/data/exositeredis
